# Generated by Django 3.2.5 on 2021-08-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('spec', models.TextField(max_length=5000, null=True)),
                ('snsLink', models.TextField(max_length=500, null=True)),
                ('blogLink', models.TextField(max_length=500, null=True)),
                ('youtubeLink', models.TextField(max_length=500, null=True)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('isLicensed', models.BooleanField(default=False)),
                ('isSubmitted', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField(null=True)),
                ('title', models.TextField(max_length=255, null=True)),
                ('introduce', models.TextField(max_length=5000, null=True)),
                ('category', models.IntegerField(null=True)),
                ('notice', models.TextField(max_length=5000, null=True)),
                ('movingPrice', models.IntegerField(default=0)),
                ('isOpen', models.BooleanField(default=True)),
                ('registerDate', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chef.chef')),
                ('regionDetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.regiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateField()),
                ('eventTime', models.CharField(max_length=100, null=True)),
                ('confirmStatus', models.IntegerField(default=0)),
                ('region', models.IntegerField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.post')),
                ('regionDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.regiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.IntegerField()),
                ('order', models.IntegerField(null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.post')),
            ],
        ),
    ]
