# Generated by Django 3.2.3 on 2021-06-26 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
                ('title', models.TextField(max_length=255)),
                ('introduce', models.TextField(max_length=5000)),
                ('spec', models.TextField(max_length=5000, null=True)),
                ('category', models.IntegerField()),
                ('notice', models.TextField(max_length=5000)),
                ('movingPrice', models.IntegerField(default=0)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chef.chef')),
                ('regionDetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.regiondetail')),
            ],
        ),
    ]
