# Generated by Django 3.1.7 on 2021-07-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0007_auto_20210630_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='snslink',
            new_name='snsLink',
        ),
    ]
