# Generated by Django 3.1.7 on 2021-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0008_auto_20210701_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='region',
            field=models.IntegerField(null=True),
        ),
    ]
