# Generated by Django 3.1.7 on 2021-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0009_auto_20210702_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduce',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='notice',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
