# Generated by Django 3.1.7 on 2021-07-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0010_auto_20210709_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
