# Generated by Django 3.2.5 on 2021-07-12 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0012_auto_20210710_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='startTime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='eventDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='eventTime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
