# Generated by Django 3.2.5 on 2021-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0013_auto_20210712_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AddField(
            model_name='schedule',
            name='payment_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='permit_status',
            field=models.IntegerField(default=1),
        ),
    ]
