# Generated by Django 3.2.5 on 2021-07-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0014_auto_20210712_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='permit_status',
            new_name='confirm_status',
        ),
    ]
