# Generated by Django 3.2.5 on 2021-07-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0018_auto_20210714_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='confirm_status',
            new_name='confirmStatus',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='payment_status',
            new_name='paymentStatus',
        ),
    ]
