# Generated by Django 3.2.5 on 2021-07-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0019_auto_20210714_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='region',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='regionDetail',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='paymentStatus',
        ),
    ]
