# Generated by Django 3.2.5 on 2021-07-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0020_auto_20210716_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
