# Generated by Django 3.2.5 on 2021-08-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_rename_specorder_file_order'),
        ('chef', '0022_auto_20210805_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='region',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='regionDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.regiondetail'),
        ),
    ]
