# Generated by Django 3.2.5 on 2021-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0023_auto_20210805_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='confirmStatus',
            field=models.IntegerField(default=0),
        ),
    ]
