# Generated by Django 3.2.5 on 2021-08-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210813_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='registerDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
