# Generated by Django 3.2.3 on 2021-06-26 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_course_schedule'),
        ('customer', '0003_hascoupon_verifynum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=5000)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.post')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.chef')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('phoneNum', models.CharField(max_length=11)),
                ('usedPoint', models.IntegerField()),
                ('payMethod', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('personNum', models.IntegerField()),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.coupon')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.schedule')),
            ],
        ),
    ]
