# Generated by Django 3.1.7 on 2021-07-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210629_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currentVer',
            field=models.IntegerField(default=0),
        ),
    ]
