# Generated by Django 3.2.5 on 2021-07-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0020_auto_20210716_1318'),
        ('customer', '0014_auto_20210714_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='regionDetail',
        ),
        migrations.AddField(
            model_name='book',
            name='paymentStatus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.schedule'),
        ),
    ]
