# Generated by Django 3.2.5 on 2021-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20210716_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='payMethod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='totalPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='usedPoint',
            field=models.IntegerField(null=True),
        ),
    ]
