# Generated by Django 3.2.5 on 2021-07-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20210718_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.hascoupon'),
        ),
    ]
