# Generated by Django 3.1.7 on 2021-06-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_auto_20210627_0726'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regiondetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
                ('category', models.IntegerField()),
                ('specOrder', models.IntegerField(null=True)),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.chef')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.course')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.post')),
            ],
        ),
    ]
