# Generated by Django 3.2.5 on 2021-08-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
                ('email', models.EmailField(max_length=254)),
                ('isChecked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='media')),
                ('category', models.IntegerField()),
                ('order', models.IntegerField(null=True)),
                ('uploadDate', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.chef')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.course')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.post')),
            ],
        ),
    ]
