# Generated by Django 3.1.7 on 2021-07-01 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20210629_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileName',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='uploadDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
