# Generated by Django 3.1.7 on 2021-07-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20210701_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fileName',
        ),
    ]
