# Generated by Django 3.1.7 on 2021-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_remove_file_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='attachment',
            field=models.FileField(upload_to='media'),
        ),
    ]
