# Generated by Django 3.2.5 on 2021-07-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0018_auto_20210714_1607'),
        ('public', '0009_auto_20210714_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.chef'),
        ),
        migrations.AlterField(
            model_name='file',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.course'),
        ),
        migrations.AlterField(
            model_name='file',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.post'),
        ),
        migrations.AlterField(
            model_name='file',
            name='specOrder',
            field=models.IntegerField(null=True),
        ),
    ]
