# Generated by Django 3.2.5 on 2021-07-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_auto_20210714_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='specOrder',
            new_name='order',
        ),
    ]
